'use client';
import { useState } from 'react';

type Output = { title: string; description: string; benefits: string[]; instagram: string; tiktok: string; keywords: string[] };
export default function Home() {
 const [product,setProduct]=useState(''); const [category,setCategory]=useState(''); const [audience,setAudience]=useState(''); const [features,setFeatures]=useState(''); const [platform,setPlatform]=useState('Shopee'); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState<Output|null>(null);
 async function generate(){setBusy(true);setError('');setResult(null);try{const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product,category,audience,features,platform})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Não foi possível gerar o conteúdo.');setResult(data.result);}catch(e){setError(e instanceof Error?e.message:'Erro inesperado.');}finally{setBusy(false)}}
 return <main><nav className="nav"><a className="brand" href="#"><span className="mark">V</span> vendora<span className="ai">AI</span></a><a className="navlink" href="#como-funciona">Como funciona</a><a className="navbutton" href="#criar">Experimentar grátis ↗</a></nav>
 <section className="hero"><div className="eyebrow"><span className="dot"/> SUA NOVA ASSISTENTE DE E-COMMERCE</div><h1>Transforme produtos em<br/><span>conteúdo que vende.</span></h1><p className="intro">Crie descrições, anúncios e ideias para redes sociais em poucos segundos. Menos tempo escrevendo, mais tempo cuidando da sua loja.</p><a className="primary" href="#criar">Criar meu primeiro anúncio <span>→</span></a><div className="trust">✦ Feita para quem vende online&nbsp; · &nbsp;Conteúdo em vários formatos</div></section>
 <section className="workspace" id="criar"><div className="formhead"><div><div className="eyebrow">✦ GERADOR INTELIGENTE</div><h2>Vamos apresentar seu produto?</h2><p>Preencha os campos e deixe a Vendora preparar o conteúdo.</p></div><div className="spark">✳</div></div><div className="fields"><label>Nome do produto<input value={product} onChange={e=>setProduct(e.target.value)} placeholder="Ex.: Óleo corporal de baunilha"/></label><div className="twocol"><label>Categoria<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Ex.: Beleza"/></label><label>Público-alvo<input value={audience} onChange={e=>setAudience(e.target.value)} placeholder="Ex.: Pessoas que gostam de autocuidado"/></label></div><label>Características e informações<textarea value={features} onChange={e=>setFeatures(e.target.value)} placeholder="Tamanho, material, diferenciais, preço... Não inclua alegações que não possa comprovar." rows={4}/></label><label>Onde pretende anunciar?<select value={platform} onChange={e=>setPlatform(e.target.value)}>{['Shopee','Instagram','TikTok','Mercado Livre','Amazon','Loja virtual','Vários canais'].map(x=><option key={x}>{x}</option>)}</select></label><button className="generate" onClick={generate} disabled={busy||!product.trim() }>{busy?'Criando conteúdo...':'✦  Gerar conteúdo'}</button>{error&&<p className="error">{error}</p>}<p className="fineprint">Revise as informações geradas antes de publicar. A IA pode cometer erros.</p></div>
 {result&&<div className="results"><div className="resulthead"><h2>Seu conteúdo está pronto ✨</h2><button className="copy" onClick={()=>navigator.clipboard.writeText([result.title,result.description,...result.benefits,result.instagram,result.tiktok,result.keywords.join(', ')].join('\n\n'))}>Copiar tudo</button></div><Result title="Título sugerido" text={result.title}/><Result title="Descrição" text={result.description}/><div className="resultbox"><h3>Benefícios em destaque</h3><ul>{result.benefits.map((x,i)=><li key={i}>{x}</li>)}</ul></div><Result title="Legenda para Instagram" text={result.instagram}/><Result title="Roteiro curto para TikTok" text={result.tiktok}/><Result title="Palavras-chave" text={result.keywords.join(' · ')}/></div>}</section>
 <section className="how" id="como-funciona"><div className="eyebrow">SIMPLES ASSIM</div><h2>Da ideia ao anúncio em três passos.</h2><div className="steps"><article><b>01</b><h3>Conte sobre o produto</h3><p>Insira o nome, categoria e os detalhes que tornam seu produto especial.</p></article><article><b>02</b><h3>Deixe a IA criar</h3><p>A Vendora organiza as informações em textos adequados ao canal escolhido.</p></article><article><b>03</b><h3>Revise e publique</h3><p>Ajuste o conteúdo à sua marca e publique quando estiver satisfeito.</p></article></div></section>
 <footer><a className="brand" href="#"><span className="mark">V</span> vendora<span className="ai">AI</span></a><span>Conteúdo melhor começa com boas informações.</span><small>© {new Date().getFullYear()} Vendora AI · Projeto em versão inicial</small></footer></main>
}
function Result({title,text}:{title:string;text:string}){return <div className="resultbox"><h3>{title}</h3><p>{text}</p></div>}
